Update make-a-bet.md
Okay-Bet/docs pull request #4
Opened 2024-08-21 16:04 UTC by Jt13-0x

2024-08-21 20:13 UTC, theSchein commented on docs/tutorial-usage/make-a-bet.md
> +The Maker is the person making the bet. The address is autopopulated witht the wallet the user logged in with, but it could technically be anyone. This individual will also be placing their own funds
'witht' spelled incorrectly

2024-08-21 20:15 UTC, theSchein commented on docs/tutorial-usage/make-a-bet.md
> +For simplicity, the Judge can be either the Maker or the Taker, though this setup is not advisable for high-stakes wagers or when dealing with oposing opinions.
i still prefer 'argumentative people' over oposing opinions at the end of this sentance

2024-08-21 20:16 UTC, theSchein commented on docs/tutorial-usage/make-a-bet.md
> +This is the amount each side puts into the bet. For example, if the wager is worth $100 then the fully funded contract will have a total of $200 in it. While the wagers are entered in USD, currently
Okay Bet's

2024-08-21 20:17 UTC, theSchein requested changes
minor nits and you are good to go

2024-08-23 01:03 UTC, Jt13-0x commented on docs/tutorial-usage/make-a-bet.md
> +This is the amount each side puts into the bet. For example, if the wager is worth $100 then the fully funded contract will have a total of $200 in it. While the wagers are entered in USD, currently
updated

2024-08-23 11:07 UTC, theSchein approved these changes

2024-08-23 11:07 UTC, merged